oooooooooooo .              .                                  .   oooooooooooo
ooooooooooo          |||||||| |||||   ||||  |||||  |||||   .        ooooooooooo
oooooooooo        .     ||    ||  || ||  || ||  || ||                oooooooooo
ooooooooo               ||    |||||  |||||| ||  || ||||         .     ooooooooo
oooooooo                ||    || ||  ||  || ||  || ||                  oooooooo
ooooooo   .             ||    ||  || ||  || |||||  |||||     .          ooooooo
oooooo        .                                                     .    oooooo
ooooo                    ||    ||  ||||  |||||   ||||    2                ooooo
oooo                     ||    || ||  || ||  || ||       0      .          oooo
ooo   .              .   || || || |||||| |||||   ||||    0          .       ooo
oo                       || || || ||  || || ||      ||   2  V  2             oo
o                         ||  ||  ||  || ||  || |||||         .               o
oo             .               .                        .                .   oo
ooo                                        .                                ooo
oooo  .            .                                 .              .      oooo
ooooo                  .    Gary & Mary Ann Martin          *             ooooo
oooooo    .                         #1 & #2                        .     oooooo
ooooooo         .                                    .                  ooooooo
oooooooo                        Castle RavenLoft          *            oooooooo
ooooooooo   .                     (913)842-0300  .                    ooooooooo
oooooooooo               *                                   .       oooooooooo
ooooooooooo      .             FidoNet @1:299/110                .  ooooooooooo
oooooooooooo                 .                         .           oooooooooooo

